BUILDPATH=.

CFLAGS=-Wall
CFLAGS+=-I./
CFLAGS+=-O0 -g
LOCAL_SRC = apt7l05sf_test_demo.c 

all:
	$(CC) $(CFLAGS) $(EXT_CFLAGS)  $(LOCAL_SRC) $(LDFLAGS)  -o apt7l05sf_test_demo 
clean:
	rm -f $(LIB) $(LIBOBJ)
